name: PR
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run npm install
        run: npm ci
      - name: Build config
        run: npm run build -- pr-${{ github.event.number }}
